//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.ProfileApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.ProfileApp.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About you.
        /// </summary>
        public static string AboutYou {
            get {
                return ResourceManager.GetString("AboutYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information about you must be maximum {1} characters long.
        /// </summary>
        public static string AboutYouMaxLength {
            get {
                return ResourceManager.GetString("AboutYouMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write some details about yourself.
        /// </summary>
        public static string AboutYouPH {
            get {
                return ResourceManager.GetString("AboutYouPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string AlertOff {
            get {
                return ResourceManager.GetString("AlertOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string AlertOn {
            get {
                return ResourceManager.GetString("AlertOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot modify this language now. Try it later.
        /// </summary>
        public static string CannotModifyLanguage {
            get {
                return ResourceManager.GetString("CannotModifyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your country.
        /// </summary>
        public static string CountryPH {
            get {
                return ResourceManager.GetString("CountryPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover photo.
        /// </summary>
        public static string CoverPhoto {
            get {
                return ResourceManager.GetString("CoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and zoom.
        /// </summary>
        public static string CropHeading {
            get {
                return ResourceManager.GetString("CropHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend requests.
        /// </summary>
        public static string FriendRequets {
            get {
                return ResourceManager.GetString("FriendRequets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be zero length.
        /// </summary>
        public static string GreaterThanZero {
            get {
                return ResourceManager.GetString("GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is required.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the languages that you want to use in Langademy.
        /// </summary>
        public static string LanguagesDesc {
            get {
                return ResourceManager.GetString("LanguagesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string LanguagesTitle {
            get {
                return ResourceManager.GetString("LanguagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your last name.
        /// </summary>
        public static string LastnamePH {
            get {
                return ResourceManager.GetString("LastnamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level is required.
        /// </summary>
        public static string LevelRequired {
            get {
                return ResourceManager.GetString("LevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size.
        /// </summary>
        public static string MaxSize {
            get {
                return ResourceManager.GetString("MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetup alerts.
        /// </summary>
        public static string MeetupReminder {
            get {
                return ResourceManager.GetString("MeetupReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum size is {0}.
        /// </summary>
        public static string MinimumSize {
            get {
                return ResourceManager.GetString("MinimumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Languages.
        /// </summary>
        public static string MyLanguages {
            get {
                return ResourceManager.GetString("MyLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your name.
        /// </summary>
        public static string NamePH {
            get {
                return ResourceManager.GetString("NamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New meetup participant.
        /// </summary>
        public static string NewMeetupParticipant {
            get {
                return ResourceManager.GetString("NewMeetupParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activity yet.
        /// </summary>
        public static string NoAcitivity {
            get {
                return ResourceManager.GetString("NoAcitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file uploaded.
        /// </summary>
        public static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meetups.
        /// </summary>
        public static string NoMeetups {
            get {
                return ResourceManager.GetString("NoMeetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications settings.
        /// </summary>
        public static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string ProfParticipants {
            get {
                return ResourceManager.GetString("ProfParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string ProfSelectLanguage {
            get {
                return ResourceManager.GetString("ProfSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your level.
        /// </summary>
        public static string SelectLevel {
            get {
                return ResourceManager.GetString("SelectLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Photo.
        /// </summary>
        public static string UpdateProfilePhoto {
            get {
                return ResourceManager.GetString("UpdateProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Cover.
        /// </summary>
        public static string UploadCover {
            get {
                return ResourceManager.GetString("UploadCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to get email notifications about.
        /// </summary>
        public static string WantToNotify {
            get {
                return ResourceManager.GetString("WantToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is of wrong format.
        /// </summary>
        public static string WrongFormat {
            get {
                return ResourceManager.GetString("WrongFormat", resourceCulture);
            }
        }
    }
}
