//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.MyWallet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyWallet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyWallet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.MyWallet.MyWallet", typeof(MyWallet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string CashoutHistory {
            get {
                return ResourceManager.GetString("CashoutHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string CashoutRequest {
            get {
                return ResourceManager.GetString("CashoutRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string MovBalance {
            get {
                return ResourceManager.GetString("MovBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits In.
        /// </summary>
        public static string MovCreditsIn {
            get {
                return ResourceManager.GetString("MovCreditsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits Out.
        /// </summary>
        public static string MovCreditsOut {
            get {
                return ResourceManager.GetString("MovCreditsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MovDate {
            get {
                return ResourceManager.GetString("MovDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MovDescription {
            get {
                return ResourceManager.GetString("MovDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string MovementsFrom {
            get {
                return ResourceManager.GetString("MovementsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last transactions.
        /// </summary>
        public static string MovementsLastTransactions {
            get {
                return ResourceManager.GetString("MovementsLastTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string MovementsTo {
            get {
                return ResourceManager.GetString("MovementsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string MovementsTransactions {
            get {
                return ResourceManager.GetString("MovementsTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string MovLastMonth {
            get {
                return ResourceManager.GetString("MovLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string MovSelect {
            get {
                return ResourceManager.GetString("MovSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string MovThisMonth {
            get {
                return ResourceManager.GetString("MovThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        public static string MovThisYear {
            get {
                return ResourceManager.GetString("MovThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (line 1).
        /// </summary>
        public static string MWAddressLine1 {
            get {
                return ResourceManager.GetString("MWAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (line 2).
        /// </summary>
        public static string MWAddressLine2 {
            get {
                return ResourceManager.GetString("MWAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t save your address because your location&apos;s taxes and your billing address&apos;s taxes differ.
        /// </summary>
        public static string MWCantSaveAddress {
            get {
                return ResourceManager.GetString("MWCantSaveAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string MWCity {
            get {
                return ResourceManager.GetString("MWCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string MWCountry {
            get {
                return ResourceManager.GetString("MWCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string MWLastName {
            get {
                return ResourceManager.GetString("MWLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MWName {
            get {
                return ResourceManager.GetString("MWName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment processed successfully.
        /// </summary>
        public static string MWOrderCompleteTitle {
            get {
                return ResourceManager.GetString("MWOrderCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to complete your address so that your purchase becomes available in your Wallet.
        /// </summary>
        public static string MWOrderCompleteWarn {
            get {
                return ResourceManager.GetString("MWOrderCompleteWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region/County.
        /// </summary>
        public static string MWRegionCounty {
            get {
                return ResourceManager.GetString("MWRegionCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region/County required.
        /// </summary>
        public static string MWRegionCountyRequired {
            get {
                return ResourceManager.GetString("MWRegionCountyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        public static string MWStateProvince {
            get {
                return ResourceManager.GetString("MWStateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province is required.
        /// </summary>
        public static string MWStateProvinceRequired {
            get {
                return ResourceManager.GetString("MWStateProvinceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        public static string MWTaxId {
            get {
                return ResourceManager.GetString("MWTaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string MWZipCode {
            get {
                return ResourceManager.GetString("MWZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of credits.
        /// </summary>
        public static string ReceiptAmountofcredits {
            get {
                return ResourceManager.GetString("ReceiptAmountofcredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your personal data or update.
        /// </summary>
        public static string ReceiptConfirmPersonalData {
            get {
                return ResourceManager.GetString("ReceiptConfirmPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Langademy Credits.
        /// </summary>
        public static string ReceiptPurchaseCredits {
            get {
                return ResourceManager.GetString("ReceiptPurchaseCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits purchase.
        /// </summary>
        public static string WalletPurchaseConcept {
            get {
                return ResourceManager.GetString("WalletPurchaseConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videocall ({0}) with {1}.
        /// </summary>
        public static string WalletVideoCallAsNative {
            get {
                return ResourceManager.GetString("WalletVideoCallAsNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videocall to native speaker ({0}): {1}.
        /// </summary>
        public static string WalletVideoCallAsStudent {
            get {
                return ResourceManager.GetString("WalletVideoCallAsStudent", resourceCulture);
            }
        }
    }
}
