//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.IndexNatives {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.IndexNatives.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have enough reputation, enter your native language&apos;s chat room and meet new people that are willing to learn your language.
        /// </summary>
        public static string INBlock2B1Text {
            get {
                return ResourceManager.GetString("INBlock2B1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start talking to students.
        /// </summary>
        public static string INBlock2B1Title {
            get {
                return ResourceManager.GetString("INBlock2B1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to your native language&apos;s room and make video calls with different people. Earn positive votes and your reputation will improve. As a result more people will want to talk to you!.
        /// </summary>
        public static string INBlock2B2Text {
            get {
                return ResourceManager.GetString("INBlock2B2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain reputation.
        /// </summary>
        public static string INBlock2B2Title {
            get {
                return ResourceManager.GetString("INBlock2B2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare the rates of other natives in your room and set your rate.
        /// </summary>
        public static string INBlock2B3Text {
            get {
                return ResourceManager.GetString("INBlock2B3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be competitive.
        /// </summary>
        public static string INBlock2B3Title {
            get {
                return ResourceManager.GetString("INBlock2B3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Langademy&apos;s prices.
        /// </summary>
        public static string INConditions {
            get {
                return ResourceManager.GetString("INConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for people that want to learn languages.
        /// </summary>
        public static string INFacesPicture {
            get {
                return ResourceManager.GetString("INFacesPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us!.
        /// </summary>
        public static string INJoin {
            get {
                return ResourceManager.GetString("INJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn money from your home.
        /// </summary>
        public static string INMainPicture {
            get {
                return ResourceManager.GetString("INMainPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time banking rooms.
        /// </summary>
        public static string INTimeBankingRooms {
            get {
                return ResourceManager.GetString("INTimeBankingRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put a price to your conversations.
        /// </summary>
        public static string INTitle {
            get {
                return ResourceManager.GetString("INTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like conversating with new people and help them to become fluent in your native language, this is your chance to &lt;strong&gt;earn some extra money from home&lt;/strong&gt;.
        /// </summary>
        public static string INTitleText {
            get {
                return ResourceManager.GetString("INTitleText", resourceCulture);
            }
        }
    }
}
