//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.JSMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JSMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.JSMessages.JSMessages", typeof(JSMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm that you accept this purchase? The scheduled lessons will be added to your calendar.
        /// </summary>
        public static string acceptunanpurchase {
            get {
                return ResourceManager.GetString("acceptunanpurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Automatic partner finder.
        /// </summary>
        public static string AutomaticPartnerFinder {
            get {
                return ResourceManager.GetString("AutomaticPartnerFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0} every month.
        /// </summary>
        public static string bymonthday {
            get {
                return ResourceManager.GetString("bymonthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0} every {1} months.
        /// </summary>
        public static string bymonthdayinterv {
            get {
                return ResourceManager.GetString("bymonthdayinterv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} of every month.
        /// </summary>
        public static string bymonthsetpos {
            get {
                return ResourceManager.GetString("bymonthsetpos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} of every {2} months.
        /// </summary>
        public static string bymonthsetposinterv {
            get {
                return ResourceManager.GetString("bymonthsetposinterv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Next language exchanges meetups.
        /// </summary>
        public static string calendarAllTitle {
            get {
                return ResourceManager.GetString("calendarAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  My next language exchange meetups.
        /// </summary>
        public static string calendarMyTitle {
            get {
                return ResourceManager.GetString("calendarMyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Received conversation requests.
        /// </summary>
        public static string calendarRecRequestsTitle {
            get {
                return ResourceManager.GetString("calendarRecRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sent conversation requests.
        /// </summary>
        public static string calendarSentRequestsTitle {
            get {
                return ResourceManager.GetString("calendarSentRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your browser does not support video calls. Try it with the latest versions of Chrome, Firefox or Opera..
        /// </summary>
        public static string CallerNoWebrtc {
            get {
                return ResourceManager.GetString("CallerNoWebrtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure you want to cancel this meetup?.
        /// </summary>
        public static string cancelmeetMB {
            get {
                return ResourceManager.GetString("cancelmeetMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure you want to cancel your request?.
        /// </summary>
        public static string cancelreqMB {
            get {
                return ResourceManager.GetString("cancelreqMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel your purchase? Your credits will be refunded to your Wallet account.
        /// </summary>
        public static string cancelunanpurchase {
            get {
                return ResourceManager.GetString("cancelunanpurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You cannot accept calls, your browser does not support calls..
        /// </summary>
        public static string cannotAcceptCalls {
            get {
                return ResourceManager.GetString("cannotAcceptCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been a problem joing the classroom. Please, refresh the page and try again. If the problem persists, please, contact us.
        /// </summary>
        public static string cannotJoinClassroom {
            get {
                return ResourceManager.GetString("cannotJoinClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Do you confirm your attendance to this meetup?.
        /// </summary>
        public static string confAttendMeetup {
            get {
                return ResourceManager.GetString("confAttendMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Blocked users cannot send you contact requests and you will never be matched with them at the Language Roulette (if you want to unblock them later you can do it from your Account Settings). ¿Are you sure you want to block this user?.
        /// </summary>
        public static string confBlockUser {
            get {
                return ResourceManager.GetString("confBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure you want to cancel your attendance to this meetup?.
        /// </summary>
        public static string confCancelMeetAttendance {
            get {
                return ResourceManager.GetString("confCancelMeetAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure you want to deactivate your account?.
        /// </summary>
        public static string confDeactivateAcc {
            get {
                return ResourceManager.GetString("confDeactivateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure you want to delete {0} from your languages?.
        /// </summary>
        public static string confDelLang {
            get {
                return ResourceManager.GetString("confDelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure you want to delete {0} from your login accounts?.
        /// </summary>
        public static string confDelLoginLink {
            get {
                return ResourceManager.GetString("confDelLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This comment will be deleted. ¿Are you sure?.
        /// </summary>
        public static string ConfDelMBPost {
            get {
                return ResourceManager.GetString("ConfDelMBPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If you downvote this topic it will be removed. ¿Are you sure?.
        /// </summary>
        public static string ConfDelMBTopic {
            get {
                return ResourceManager.GetString("ConfDelMBTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this education line from your profile?.
        /// </summary>
        public static string confDelTeacherEdu {
            get {
                return ResourceManager.GetString("confDelTeacherEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this position from your profile?.
        /// </summary>
        public static string confDelTeacherPosition {
            get {
                return ResourceManager.GetString("confDelTeacherPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your rates for teaching this language?.
        /// </summary>
        public static string confDelTeacherRate {
            get {
                return ResourceManager.GetString("confDelTeacherRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Do you want to save your changes before closing?.
        /// </summary>
        public static string confirmSave {
            get {
                return ResourceManager.GetString("confirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Acording to your country&apos;s laws, we need to know your real location in order to store your billing address. If you click OK your navigator will ask for your location again..
        /// </summary>
        public static string ConfirnGetLocation {
            get {
                return ResourceManager.GetString("ConfirnGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Connecting with {0}....
        /// </summary>
        public static string connectingWithPartner {
            get {
                return ResourceManager.GetString("connectingWithPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  A connection error has ocurred during the call. The call will be finished.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Error during the call.
        /// </summary>
        public static string ConnectionErrorTitle {
            get {
                return ResourceManager.GetString("ConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Continue the call.
        /// </summary>
        public static string ContinueVideoCall {
            get {
                return ResourceManager.GetString("ContinueVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  conversation-exchange-meetups.
        /// </summary>
        public static string conversationexchangemeetups {
            get {
                return ResourceManager.GetString("conversationexchangemeetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  There&apos;s a meetup scheduled at {0}​.
        /// </summary>
        public static string CRMeetupTime {
            get {
                return ResourceManager.GetString("CRMeetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nobody has proposed conversation topics for this meetup.
        /// </summary>
        public static string CRNoTopicsProposed {
            get {
                return ResourceManager.GetString("CRNoTopicsProposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string dailyfreq {
            get {
                return ResourceManager.GetString("dailyfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every {0} days.
        /// </summary>
        public static string dailyfreqinterv {
            get {
                return ResourceManager.GetString("dailyfreqinterv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit availability.
        /// </summary>
        public static string EditAvailability {
            get {
                return ResourceManager.GetString("EditAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  End the call.
        /// </summary>
        public static string EndVideoCall {
            get {
                return ResourceManager.GetString("EndVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sorry, but something went wrong.
        /// </summary>
        public static string errorSt {
            get {
                return ResourceManager.GetString("errorSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Give us your opinion.
        /// </summary>
        public static string FeedbackOpinion {
            get {
                return ResourceManager.GetString("FeedbackOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Thank you for submitting your feedback!.
        /// </summary>
        public static string FeedbackSuccess {
            get {
                return ResourceManager.GetString("FeedbackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Filter Meetups.
        /// </summary>
        public static string FilterMeetups {
            get {
                return ResourceManager.GetString("FilterMeetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Filter Users.
        /// </summary>
        public static string FilterRoomUsers {
            get {
                return ResourceManager.GetString("FilterRoomUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        public static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are so sorry, but your browser cannot share your geolocation with Langademy, so you are not allowed to update your invoicing data. We recommend you to use Google Chrome for the best experience at Langademy.
        /// </summary>
        public static string GeoNoAvailable {
            get {
                return ResourceManager.GetString("GeoNoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have detected that you denied the permission to share your geolocation with Langademy. Before you update your invoicing data, you must allow to share it (Your geolocation will remain private and it will not be published anywhere).
        /// </summary>
        public static string GeoNoPermission {
            get {
                return ResourceManager.GetString("GeoNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Connection to the Langademy servers has been lost. Trying to reconnect....
        /// </summary>
        public static string GlobalNetworkError {
            get {
                return ResourceManager.GetString("GlobalNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Complete your profile.
        /// </summary>
        public static string IncompleteProfile {
            get {
                return ResourceManager.GetString("IncompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Invitations sent correctly!.
        /// </summary>
        public static string InvitsSent {
            get {
                return ResourceManager.GetString("InvitsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining the classroom.
        /// </summary>
        public static string JoiningClassroom {
            get {
                return ResourceManager.GetString("JoiningClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Click the block above to view your profile options,.
        /// </summary>
        public static string LayoutTrip1Step1 {
            get {
                return ResourceManager.GetString("LayoutTrip1Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Click your name and go to View Profile so you can add the languages you want to practice,.
        /// </summary>
        public static string LayoutTrip1Step2 {
            get {
                return ResourceManager.GetString("LayoutTrip1Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Do you really want to leave?.
        /// </summary>
        public static string LeaveAppConfirmation {
            get {
                return ResourceManager.GetString("LeaveAppConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Do you really want to leave the videocall?.
        /// </summary>
        public static string LeaveCall {
            get {
                return ResourceManager.GetString("LeaveCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure of leaving the room?.
        /// </summary>
        public static string LeaveRoomConfirmation {
            get {
                return ResourceManager.GetString("LeaveRoomConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You are in a video call.
        /// </summary>
        public static string leaveVC {
            get {
                return ResourceManager.GetString("leaveVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Did you like chatting with {0}?.
        /// </summary>
        public static string LikeSentence {
            get {
                return ResourceManager.GetString("LikeSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Login with.
        /// </summary>
        public static string LoginOrSignup {
            get {
                return ResourceManager.GetString("LoginOrSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your meetup is about to begin.
        /// </summary>
        public static string meetupAlert {
            get {
                return ResourceManager.GetString("meetupAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Reminder.
        /// </summary>
        public static string meetupAlertTitle {
            get {
                return ResourceManager.GetString("meetupAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Meetup Board.
        /// </summary>
        public static string MeetupBoard {
            get {
                return ResourceManager.GetString("MeetupBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Choose a topic for your meetup.
        /// </summary>
        public static string meetupSelectTopic {
            get {
                return ResourceManager.GetString("meetupSelectTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Network connection error.
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Connection to the Langademy servers has been lost. Try to call again after the connection is restored..
        /// </summary>
        public static string NetworkErrorInVideo {
            get {
                return ResourceManager.GetString("NetworkErrorInVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New availability.
        /// </summary>
        public static string NewAvailability {
            get {
                return ResourceManager.GetString("NewAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We couldn&apos;t detect a webcam or a microphone in your partner&apos;s device, your call will be finished.
        /// </summary>
        public static string NoCameraNorMic {
            get {
                return ResourceManager.GetString("NoCameraNorMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Camera and microphone not detected.
        /// </summary>
        public static string NoCamTitle {
            get {
                return ResourceManager.GetString("NoCamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Time Bank notification.
        /// </summary>
        public static string NoChatHours {
            get {
                return ResourceManager.GetString("NoChatHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your partner couldn&apos;t connect the camera or the microphone and the call has been finished.
        /// </summary>
        public static string NoMediaAcceptance {
            get {
                return ResourceManager.GetString("NoMediaAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cam/Microphone permission.
        /// </summary>
        public static string NoMediaTitle {
            get {
                return ResourceManager.GetString("NoMediaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We couldn&apos;t detect a webcam or a microphone in your device, your call will be finished.
        /// </summary>
        public static string NoOwnCameraNorMic {
            get {
                return ResourceManager.GetString("NoOwnCameraNorMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You didn&apos;t grant access to your camera/microphone in your navigator. You can grant access to them and continue the call or leave the call now..
        /// </summary>
        public static string NoOwnMediaAcceptance {
            get {
                return ResourceManager.GetString("NoOwnMediaAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your browser does not support this page.
        /// </summary>
        public static string NoSupported {
            get {
                return ResourceManager.GetString("NoSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No, thanks.
        /// </summary>
        public static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot update your rates during a videocall.
        /// </summary>
        public static string NotUpdateInVideo {
            get {
                return ResourceManager.GetString("NotUpdateInVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your browser does not support video calls.
        /// </summary>
        public static string NoWebrtc {
            get {
                return ResourceManager.GetString("NoWebrtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You have finished the call.
        /// </summary>
        public static string OwnFinished {
            get {
                return ResourceManager.GetString("OwnFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Participantes.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You can call {0} when you&apos;re both online.
        /// </summary>
        public static string PrMeetupBegin {
            get {
                return ResourceManager.GetString("PrMeetupBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} and you are online. You can start a videocall whenever you want.
        /// </summary>
        public static string PrMeetupBeginBoth {
            get {
                return ResourceManager.GetString("PrMeetupBeginBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Private conversation starts now.
        /// </summary>
        public static string PrMeetupBeginTitle {
            get {
                return ResourceManager.GetString("PrMeetupBeginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The conversation duration that you scheduled has been exceeded. Add {0} to your contact list for speaking at any time.
        /// </summary>
        public static string PrMeetupOver {
            get {
                return ResourceManager.GetString("PrMeetupOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Private conversation is over.
        /// </summary>
        public static string PrMeetupOverTitle {
            get {
                return ResourceManager.GetString("PrMeetupOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Profile Edit.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add the languages you know and the languages you want to learn. You can only enter the rooms of the languages you have in your profile..
        /// </summary>
        public static string ProfileTripStep1 {
            get {
                return ResourceManager.GetString("ProfileTripStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You can always go back to the home page by clicking the home button.
        /// </summary>
        public static string ProfileTripStep2 {
            get {
                return ResourceManager.GetString("ProfileTripStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Are you sure you want to reject this conversation request?.
        /// </summary>
        public static string rejectreqMB {
            get {
                return ResourceManager.GetString("rejectreqMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject this purchase? Make sure the student understands the reason.
        /// </summary>
        public static string rejectunanpurchase {
            get {
                return ResourceManager.GetString("rejectunanpurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} has finished the call.
        /// </summary>
        public static string RemoteFinished {
            get {
                return ResourceManager.GetString("RemoteFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report issue.
        /// </summary>
        public static string ReportIssue {
            get {
                return ResourceManager.GetString("ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Request conversation.
        /// </summary>
        public static string RequestConv {
            get {
                return ResourceManager.GetString("RequestConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request mediation.
        /// </summary>
        public static string RequestMediation {
            get {
                return ResourceManager.GetString("RequestMediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request rate.
        /// </summary>
        public static string RequestRate {
            get {
                return ResourceManager.GetString("RequestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check at least one box.
        /// </summary>
        public static string RequireOneErrorMsg {
            get {
                return ResourceManager.GetString("RequireOneErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule lesson.
        /// </summary>
        public static string RescheduleLesson {
            get {
                return ResourceManager.GetString("RescheduleLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Click the menu button to see its options.
        /// </summary>
        public static string RoomTripStep1 {
            get {
                return ResourceManager.GetString("RoomTripStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Click on a connected user to make a videocall, check his profile or to send a connection request.
        /// </summary>
        public static string RoomTripStep2 {
            get {
                return ResourceManager.GetString("RoomTripStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You will be able to make private video calls and chats without entering the rooms.
        /// </summary>
        public static string RoomTripStep3 {
            get {
                return ResourceManager.GetString("RoomTripStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Check the next meetups of this room!,.
        /// </summary>
        public static string RoomTripStep4 {
            get {
                return ResourceManager.GetString("RoomTripStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If the room is empty, create meetups at the time and day you want and try to gather your contacts there.
        /// </summary>
        public static string RoomTripStep5 {
            get {
                return ResourceManager.GetString("RoomTripStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  We couldn&apos;t connect you with your partner due to the security level of your networks.
        /// </summary>
        public static string RouletteCannotConnect {
            get {
                return ResourceManager.GetString("RouletteCannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} times.
        /// </summary>
        public static string rrulecount {
            get {
                return ResourceManager.GetString("rrulecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts on {0}.
        /// </summary>
        public static string rruledtstart {
            get {
                return ResourceManager.GetString("rruledtstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only once.
        /// </summary>
        public static string rruleonlyonce {
            get {
                return ResourceManager.GetString("rruleonlyonce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0} to {1}.
        /// </summary>
        public static string rruletimespan {
            get {
                return ResourceManager.GetString("rruletimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until {0}.
        /// </summary>
        public static string rruleuntil {
            get {
                return ResourceManager.GetString("rruleuntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date of your lesson.
        /// </summary>
        public static string seldateoneless {
            get {
                return ResourceManager.GetString("seldateoneless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least the date of your first lesson. You can schedule the remaining ones at any time.
        /// </summary>
        public static string seldatepack {
            get {
                return ResourceManager.GetString("seldatepack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date of your lesson (minimum: 30 minutes, maximum: 2 hours).
        /// </summary>
        public static string seldatepago {
            get {
                return ResourceManager.GetString("seldatepago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Select your language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        public static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Time Bank.
        /// </summary>
        public static string TimeBank {
            get {
                return ResourceManager.GetString("TimeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Timebanking room.
        /// </summary>
        public static string TimeBankRoom {
            get {
                return ResourceManager.GetString("TimeBankRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter the chat rooms if you want to chat or make calls with native speakers. You can use your Wallet and/or time banking accounts to make video calls.
        /// </summary>
        public static string Trip2Step1 {
            get {
                return ResourceManager.GetString("Trip2Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Find users that suit your preferences. Click the Search button and start contacting them!.
        /// </summary>
        public static string Trip3Step1 {
            get {
                return ResourceManager.GetString("Trip3Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  I&apos;m an expert!.
        /// </summary>
        public static string TripExpert {
            get {
                return ResourceManager.GetString("TripExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Skip all steps.
        /// </summary>
        public static string TripExpert2 {
            get {
                return ResourceManager.GetString("TripExpert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Got it!.
        /// </summary>
        public static string TripFinish {
            get {
                return ResourceManager.GetString("TripFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Next.
        /// </summary>
        public static string TripNext {
            get {
                return ResourceManager.GetString("TripNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You probably are on a secure entrerprise network. Try to connect from another network.
        /// </summary>
        public static string TurnSecureServer {
            get {
                return ResourceManager.GetString("TurnSecureServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Profile Photo.
        /// </summary>
        public static string UpdateProfilePhoto {
            get {
                return ResourceManager.GetString("UpdateProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} has entered the room. Join the chat!.
        /// </summary>
        public static string UserRoomEntrance {
            get {
                return ResourceManager.GetString("UserRoomEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  earned.
        /// </summary>
        public static string vcEarned {
            get {
                return ResourceManager.GetString("vcEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  spent.
        /// </summary>
        public static string vcSpent {
            get {
                return ResourceManager.GetString("vcSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Videocall.
        /// </summary>
        public static string VideoCall {
            get {
                return ResourceManager.GetString("VideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Waiting for you to give permission in your browser to use your camera....
        /// </summary>
        public static string WaitingForCamera {
            get {
                return ResourceManager.GetString("WaitingForCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for {0} to join the classroom.
        /// </summary>
        public static string WaitingPartnerClassroom {
            get {
                return ResourceManager.GetString("WaitingPartnerClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for permission to use your camera....
        /// </summary>
        public static string WaitingTo {
            get {
                return ResourceManager.GetString("WaitingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Wallet room rate.
        /// </summary>
        public static string WalletRateTitle {
            get {
                return ResourceManager.GetString("WalletRateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Wallet room.
        /// </summary>
        public static string WalletRoom {
            get {
                return ResourceManager.GetString("WalletRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You can&apos;t change the language during a videocall.
        /// </summary>
        public static string warnnochangelng {
            get {
                return ResourceManager.GetString("warnnochangelng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly, every {0}.
        /// </summary>
        public static string weeklyfreq {
            get {
                return ResourceManager.GetString("weeklyfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every {0} weeks, on {1}.
        /// </summary>
        public static string weeklyfreqinterv {
            get {
                return ResourceManager.GetString("weeklyfreqinterv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
