//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Index {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Index.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;#&quot;&gt;&lt;strong&gt;meet-up board&lt;/strong&gt;&lt;/a&gt;.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMING SOON.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us!.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s free!.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet new people.
        /// </summary>
        public static string KnowPeople {
            get {
                return ResourceManager.GetString("KnowPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  is a videochat roulette where you will find native speakers to practise your favourite languages.
        /// </summary>
        public static string Langroulette {
            get {
                return ResourceManager.GetString("Langroulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your online language exchange community.
        /// </summary>
        public static string LanguageEx {
            get {
                return ResourceManager.GetString("LanguageEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn languages and get fluent talking to people all over the world.
        /// </summary>
        public static string LearnLang {
            get {
                return ResourceManager.GetString("LearnLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or join a language meet-up and let your partners know when u will be joining a meet-up in the {0}.
        /// </summary>
        public static string ManageMeetup {
            get {
                return ResourceManager.GetString("ManageMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next meet-ups in Langroulette.
        /// </summary>
        public static string NextMeetups {
            get {
                return ResourceManager.GetString("NextMeetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak in your native language and we will give you the same time so you can practise other languages.
        /// </summary>
        public static string SpeakNative {
            get {
                return ResourceManager.GetString("SpeakNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Langademy.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you prefer it.
        /// </summary>
        public static string WhenPossible {
            get {
                return ResourceManager.GetString("WhenPossible", resourceCulture);
            }
        }
    }
}
