//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Index {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Index.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;/MeetupBoard&quot; class=&quot;link&quot;&gt;&lt;strong&gt;meetup board&lt;/strong&gt;&lt;/a&gt;.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMING SOON.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us!.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn languages for free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string IndAbout {
            get {
                return ResourceManager.GetString("IndAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already subscribed.
        /// </summary>
        public static string IndexAlreadySubscribed {
            get {
                return ResourceManager.GetString("IndexAlreadySubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you are ready!.
        /// </summary>
        public static string IndexFooterSt1 {
            get {
                return ResourceManager.GetString("IndexFooterSt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you complete the registration form, you will be able to upload your profile picture, add more languages and fill in the rest of your profile.
        /// </summary>
        public static string IndexFooterSt2 {
            get {
                return ResourceManager.GetString("IndexFooterSt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then check the scheduled meetups and join or create your own.
        /// </summary>
        public static string IndexFooterSt3 {
            get {
                return ResourceManager.GetString("IndexFooterSt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any doubt, send us a message from your Conversations Panel. We will be happy to help you.
        /// </summary>
        public static string IndexFooterSt4 {
            get {
                return ResourceManager.GetString("IndexFooterSt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language exchange.
        /// </summary>
        public static string IndexLanguageExchange1 {
            get {
                return ResourceManager.GetString("IndexLanguageExchange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of time you have to speak with natives by videoconference is the same amount of time that you use to teach your native language to others.
        /// </summary>
        public static string IndexLanguageExchange2 {
            get {
                return ResourceManager.GetString("IndexLanguageExchange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It works like a tandem, but you decide who you partners are, when and in which language you want to chat with .
        /// </summary>
        public static string IndexLanguageExchange3 {
            get {
                return ResourceManager.GetString("IndexLanguageExchange3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will begin with 5 free hours so you can try Langademy&apos;s language exchange.
        /// </summary>
        public static string IndexLanguageExchange4 {
            get {
                return ResourceManager.GetString("IndexLanguageExchange4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Langademy, your language exchange community.
        /// </summary>
        public static string IndexLogoAlt {
            get {
                return ResourceManager.GetString("IndexLogoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The easiest way to meet a new partner.
        /// </summary>
        public static string IndexLR1 {
            get {
                return ResourceManager.GetString("IndexLR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug in your webcam and your microphone and enter the room of the language you want to practice.
        /// </summary>
        public static string IndexLR2 {
            get {
                return ResourceManager.GetString("IndexLR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will find you a partner to speak with you that meets your filter.
        /// </summary>
        public static string IndexLR3 {
            get {
                return ResourceManager.GetString("IndexLR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be kind ;-).
        /// </summary>
        public static string IndexLR4 {
            get {
                return ResourceManager.GetString("IndexLR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to speak with another person, click next and we will find you another match.
        /// </summary>
        public static string IndexLR5 {
            get {
                return ResourceManager.GetString("IndexLR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create converstion exchange meetups in the meetup board.
        /// </summary>
        public static string IndexMBPictureAlt {
            get {
                return ResourceManager.GetString("IndexMBPictureAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take advantage of Langademy&apos;s Meetup Board.
        /// </summary>
        public static string IndexMeetingBoard1 {
            get {
                return ResourceManager.GetString("IndexMeetingBoard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All for one!.
        /// </summary>
        public static string IndexMeetingBoard2 {
            get {
                return ResourceManager.GetString("IndexMeetingBoard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When do you want to have a conversation? Contribute to enriching the language exchange community by scheduling meetups for the days and hours you want to enter the Language Roulette. Make it in time so people will have time to join the meetup.
        /// </summary>
        public static string IndexMeetingBoard3 {
            get {
                return ResourceManager.GetString("IndexMeetingBoard3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If someone else has organized a meetup, you can join the meetup. It&apos;s just a click! The other attendants will like it if you join them.
        /// </summary>
        public static string IndexMeetingBoard4 {
            get {
                return ResourceManager.GetString("IndexMeetingBoard4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also share the meetup link in social networks so more people can join the meetup. The more, the merrier :-).
        /// </summary>
        public static string IndexMeetingBoard5 {
            get {
                return ResourceManager.GetString("IndexMeetingBoard5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you like to conversate with your partner?.
        /// </summary>
        public static string IndexPartners1 {
            get {
                return ResourceManager.GetString("IndexPartners1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote him in his profile!.
        /// </summary>
        public static string IndexPartners2 {
            get {
                return ResourceManager.GetString("IndexPartners2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send him a contact request.
        /// </summary>
        public static string IndexPartners3 {
            get {
                return ResourceManager.GetString("IndexPartners3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When he accepts your request you will be able to make videoconferences without entering the Language Roulette.
        /// </summary>
        public static string IndexPartners4 {
            get {
                return ResourceManager.GetString("IndexPartners4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What languages do you speak? Which is your level?.
        /// </summary>
        public static string IndexQuestion1 {
            get {
                return ResourceManager.GetString("IndexQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you from? What are your interests?.
        /// </summary>
        public static string IndexQuestion2 {
            get {
                return ResourceManager.GetString("IndexQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are ready to talk in Spanish, English or the language you want!.
        /// </summary>
        public static string IndexReady {
            get {
                return ResourceManager.GetString("IndexReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search language exchange partners.
        /// </summary>
        public static string IndexSearchPartners {
            get {
                return ResourceManager.GetString("IndexSearchPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string IndexSeeMore {
            get {
                return ResourceManager.GetString("IndexSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your avatar and cover photos.
        /// </summary>
        public static string IndexStep2 {
            get {
                return ResourceManager.GetString("IndexStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are working on amazing tools for you! Send us your email address and we will keep you informed about new updates.
        /// </summary>
        public static string IndexTeacherSubscribe {
            get {
                return ResourceManager.GetString("IndexTeacherSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your interest in next Langademy updates for teachers. If you have any suggestions or doubts don&apos;t hesitate to contact us at contact@langademy.com. We will keep you informed!.
        /// </summary>
        public static string IndexTeacherSubscribeConfirm {
            get {
                return ResourceManager.GetString("IndexTeacherSubscribeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a teacher?.
        /// </summary>
        public static string IndexTeacherTitle {
            get {
                return ResourceManager.GetString("IndexTeacherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time banking.
        /// </summary>
        public static string IndexTimeBank1 {
            get {
                return ResourceManager.GetString("IndexTimeBank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your time balance to know if you have to speak in your native language.
        /// </summary>
        public static string IndexTimeBank2 {
            get {
                return ResourceManager.GetString("IndexTimeBank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the time banking rules in order to know when a videochat conversation will add or substract time from your Time Bank account.
        /// </summary>
        public static string IndexTimeBank3 {
            get {
                return ResourceManager.GetString("IndexTimeBank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using your state your contacts will know if you are available to receive videocalls.
        /// </summary>
        public static string IndexTimeBank4 {
            get {
                return ResourceManager.GetString("IndexTimeBank4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn spanish, german, english, french or any language online with Langademy. By using the  you can find native speakers to practice your favourite languages.
        /// </summary>
        public static string IndLangroulette {
            get {
                return ResourceManager.GetString("IndLangroulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string IndLanguages {
            get {
                return ResourceManager.GetString("IndLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next meetups to practice languages.
        /// </summary>
        public static string IndNextMeetups {
            get {
                return ResourceManager.GetString("IndNextMeetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string IndParticipants {
            get {
                return ResourceManager.GetString("IndParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy
        ///.
        /// </summary>
        public static string IndPrivacy {
            get {
                return ResourceManager.GetString("IndPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string IndRegister {
            get {
                return ResourceManager.GetString("IndRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string IndTerms {
            get {
                return ResourceManager.GetString("IndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation exchange.
        /// </summary>
        public static string KnowPeople {
            get {
                return ResourceManager.GetString("KnowPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your online language exchange community.
        /// </summary>
        public static string LanguageEx {
            get {
                return ResourceManager.GetString("LanguageEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn languages and become fluent talking to people all over the world.
        /// </summary>
        public static string LearnLang {
            get {
                return ResourceManager.GetString("LearnLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Create meetups to exchange languages when you want and invite your partners to join!.
        /// </summary>
        public static string ManageMeetup {
            get {
                return ResourceManager.GetString("ManageMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up and start learning languages for free.
        /// </summary>
        public static string RegisterAndCompleteProfile {
            get {
                return ResourceManager.GetString("RegisterAndCompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak in your native language and we will give you the same amount of time to practice other languages. Make conversation exchange your trade!.
        /// </summary>
        public static string SpeakNative {
            get {
                return ResourceManager.GetString("SpeakNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try conversation exchange with the Language Roulette.
        /// </summary>
        public static string TryLanguageRoulette {
            get {
                return ResourceManager.GetString("TryLanguageRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Langademy!.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice the language you want, when you want.
        /// </summary>
        public static string WhenPossible {
            get {
                return ResourceManager.GetString("WhenPossible", resourceCulture);
            }
        }
    }
}
