//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ViewModels.VideoChatReport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VideoChatReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideoChatReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ViewModels.VideoChatReport.VideoChatReport", typeof(VideoChatReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you like chatting with {0} ?.
        /// </summary>
        public static string LikeSentence {
            get {
                return ResourceManager.GetString("LikeSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls between natives have no cost for you.
        /// </summary>
        public static string NoCostNatives {
            get {
                return ResourceManager.GetString("NoCostNatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls between non-native speakers have no cost for you.
        /// </summary>
        public static string NoCostNoNatives {
            get {
                return ResourceManager.GetString("NoCostNoNatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished the call.
        /// </summary>
        public static string OwnFinished {
            get {
                return ResourceManager.GetString("OwnFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has finished the call.
        /// </summary>
        public static string RemoteFinished {
            get {
                return ResourceManager.GetString("RemoteFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking in a non-native language with a native user has a cost for you.
        /// </summary>
        public static string VCLearnLang {
            get {
                return ResourceManager.GetString("VCLearnLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls that are shorter than a minute have no cost.
        /// </summary>
        public static string VCNoMinimunTime {
            get {
                return ResourceManager.GetString("VCNoMinimunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking in your language to a partner that has lower level than you gives you additional time.
        /// </summary>
        public static string VCShowYourLang {
            get {
                return ResourceManager.GetString("VCShowYourLang", resourceCulture);
            }
        }
    }
}
