//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Routes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Routes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Routes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Routes.Routes", typeof(Routes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language/{selectedCulture}/.
        /// </summary>
        public static string bloglanguage {
            get {
                return ResourceManager.GetString("bloglanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/chat-rooms.
        /// </summary>
        public static string chat_rooms {
            get {
                return ResourceManager.GetString("chat-rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conversation-exchange-meetups.
        /// </summary>
        public static string conversation_exchange_meetups {
            get {
                return ResourceManager.GetString("conversation-exchange-meetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earn-as-conversation-partner.
        /// </summary>
        public static string earn_as_conversation_partner {
            get {
                return ResourceManager.GetString("earn-as-conversation-partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/how-does-time-banking-work.
        /// </summary>
        public static string how_does_time_banking_work {
            get {
                return ResourceManager.GetString("how-does-time-banking-work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/how-to-meet-partners.
        /// </summary>
        public static string how_to_meet_partners {
            get {
                return ResourceManager.GetString("how-to-meet-partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/how-to-request-private-conversation.
        /// </summary>
        public static string how_to_request_private_conversation {
            get {
                return ResourceManager.GetString("how-to-request-private-conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/how-to-set-availability.
        /// </summary>
        public static string how_to_set_availability {
            get {
                return ResourceManager.GetString("how-to-set-availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/how-to-set-rate.
        /// </summary>
        public static string how_to_set_rate {
            get {
                return ResourceManager.GetString("how-to-set-rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/langademy-state.
        /// </summary>
        public static string langademy_state {
            get {
                return ResourceManager.GetString("langademy-state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language-exchange.
        /// </summary>
        public static string language_exchange {
            get {
                return ResourceManager.GetString("language-exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language-exchange-partners.
        /// </summary>
        public static string language_exchange_partners {
            get {
                return ResourceManager.GetString("language-exchange-partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/language-learners-how-to-start.
        /// </summary>
        public static string language_learners_how_to_start {
            get {
                return ResourceManager.GetString("language-learners-how-to-start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn-languages-online.
        /// </summary>
        public static string learn_languages {
            get {
                return ResourceManager.GetString("learn-languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to native-partners-language-exchange.
        /// </summary>
        public static string native_partners_exchange {
            get {
                return ResourceManager.GetString("native-partners-exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/natives-how-to-start.
        /// </summary>
        public static string natives_how_to_start {
            get {
                return ResourceManager.GetString("natives-how-to-start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other-language-resources.
        /// </summary>
        public static string OtherLangResources {
            get {
                return ResourceManager.GetString("OtherLangResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paid-converstions-with-natives.
        /// </summary>
        public static string paid_converstions_with_natives {
            get {
                return ResourceManager.GetString("paid-converstions-with-natives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pricing.
        /// </summary>
        public static string pricing {
            get {
                return ResourceManager.GetString("pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search-language-students.
        /// </summary>
        public static string search_language_students {
            get {
                return ResourceManager.GetString("search-language-students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/time-banking-indroduction.
        /// </summary>
        public static string time_banking_indroduction {
            get {
                return ResourceManager.GetString("time-banking-indroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/my-wallet-introduction.
        /// </summary>
        public static string wallet_introduction {
            get {
                return ResourceManager.GetString("wallet-introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/wallet-native-fees.
        /// </summary>
        public static string wallet_native_fees {
            get {
                return ResourceManager.GetString("wallet-native-fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/wallet-video-calls-introduction.
        /// </summary>
        public static string wallet_video_calls_intro {
            get {
                return ResourceManager.GetString("wallet-video-calls-intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/wallet-withdrawals.
        /// </summary>
        public static string wallet_withdrawals {
            get {
                return ResourceManager.GetString("wallet-withdrawals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/what-you-can-do-in-langademy.
        /// </summary>
        public static string what_you_can_do_in_langademy {
            get {
                return ResourceManager.GetString("what-you-can-do-in-langademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help/why-complete-profile.
        /// </summary>
        public static string why_complete_profile {
            get {
                return ResourceManager.GetString("why-complete-profile", resourceCulture);
            }
        }
    }
}
