//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models.Tiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.Tiles.Tiles", typeof(Tiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account quick set up.
        /// </summary>
        public static string ConfigurationIntro {
            get {
                return ResourceManager.GetString("ConfigurationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you make a videocall in a language that is not your native language, you spend time from your Time Bank account. If you speak to a non-native in your native language, you will be rewarded with time in your account..
        /// </summary>
        public static string HoursBagIntro {
            get {
                return ResourceManager.GetString("HoursBagIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Friends.
        /// </summary>
        public static string Invite_Friends {
            get {
                return ResourceManager.GetString("Invite_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create meetups and practice the language you want!.
        /// </summary>
        public static string MeetupBoardIntro {
            get {
                return ResourceManager.GetString("MeetupBoardIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My evolution.
        /// </summary>
        public static string My_evolution {
            get {
                return ResourceManager.GetString("My_evolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit your profile here, for example, you can add or edit the languages you are willing to learn..
        /// </summary>
        public static string ProfileEditionIntro {
            get {
                return ResourceManager.GetString("ProfileEditionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search exchange partners.
        /// </summary>
        public static string SearchUsers {
            get {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string ShowMoreHelp {
            get {
                return ResourceManager.GetString("ShowMoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string TileBlog {
            get {
                return ResourceManager.GetString("TileBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string TileChat {
            get {
                return ResourceManager.GetString("TileChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string TileConfiguration {
            get {
                return ResourceManager.GetString("TileConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string TileContacts {
            get {
                return ResourceManager.GetString("TileContacts", resourceCulture);
            }
        }
    }
}
