//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.RightPanel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RightPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RightPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.RightPanel.RightPanel", typeof(RightPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All contacts.
        /// </summary>
        public static string AllContacts {
            get {
                return ResourceManager.GetString("AllContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is lost. Reloading in.
        /// </summary>
        public static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to see your contacts.
        /// </summary>
        public static string ContactsNoLogged {
            get {
                return ResourceManager.GetString("ContactsNoLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no contacts yet. Go to {0} and meet new partners!.
        /// </summary>
        public static string NoContacts {
            get {
                return ResourceManager.GetString("NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any messages.
        /// </summary>
        public static string NoMessages {
            get {
                return ResourceManager.GetString("NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any notifications.
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to see your notifications.
        /// </summary>
        public static string NotificationsNoLogged {
            get {
                return ResourceManager.GetString("NotificationsNoLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload now.
        /// </summary>
        public static string ReloadNow {
            get {
                return ResourceManager.GetString("ReloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string RPContacts {
            get {
                return ResourceManager.GetString("RPContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string RPFilterAdd {
            get {
                return ResourceManager.GetString("RPFilterAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All languages.
        /// </summary>
        public static string RPFilterAllLanguages {
            get {
                return ResourceManager.GetString("RPFilterAllLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string RPFilterAllPeople {
            get {
                return ResourceManager.GetString("RPFilterAllPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RPFilterCancel {
            get {
                return ResourceManager.GetString("RPFilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string RPFilterLanguages {
            get {
                return ResourceManager.GetString("RPFilterLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People you haven&apos;t chatted with.
        /// </summary>
        public static string RPFilterNotTalketTo {
            get {
                return ResourceManager.GetString("RPFilterNotTalketTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string RPFilterOk {
            get {
                return ResourceManager.GetString("RPFilterOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just online.
        /// </summary>
        public static string RPFilterOnline {
            get {
                return ResourceManager.GetString("RPFilterOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People you have chatted with.
        /// </summary>
        public static string RPFilterTalkedTo {
            get {
                return ResourceManager.GetString("RPFilterTalkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string RPSearch {
            get {
                return ResourceManager.GetString("RPSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videocall.
        /// </summary>
        public static string RPVideocall {
            get {
                return ResourceManager.GetString("RPVideocall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        public static string RPViewProfile {
            get {
                return ResourceManager.GetString("RPViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videocall.
        /// </summary>
        public static string Videocall {
            get {
                return ResourceManager.GetString("Videocall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        public static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write here.
        /// </summary>
        public static string WriteHere {
            get {
                return ResourceManager.GetString("WriteHere", resourceCulture);
            }
        }
    }
}
