//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.HoursBag {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HoursBag {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HoursBag() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.HoursBag.HoursBag", typeof(HoursBag).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to earn extra time?.
        /// </summary>
        public static string AdditionalTime {
            get {
                return ResourceManager.GetString("AdditionalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept.
        /// </summary>
        public static string Concept {
            get {
                return ResourceManager.GetString("Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn more hours.
        /// </summary>
        public static string EarnButton {
            get {
                return ResourceManager.GetString("EarnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your friends to &lt;strong&gt;Langademy&lt;/strong&gt; now! each registered friend will add 30 minutes to your hoursbag! Or follow us in the social networks and you will earn an extra hour!.
        /// </summary>
        public static string InviteEarn {
            get {
                return ResourceManager.GetString("InviteEarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a mail and push space or &quot; ; &quot;.
        /// </summary>
        public static string MailInstruction {
            get {
                return ResourceManager.GetString("MailInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Balance.
        /// </summary>
        public static string RemainingBagTime {
            get {
                return ResourceManager.GetString("RemainingBagTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Balance.
        /// </summary>
        public static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invitation.
        /// </summary>
        public static string SendInvitation {
            get {
                return ResourceManager.GetString("SendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to your account.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Bank.
        /// </summary>
        public static string TitleHoursBag {
            get {
                return ResourceManager.GetString("TitleHoursBag", resourceCulture);
            }
        }
    }
}
