//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Help.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chat rooms are the place where you can go to exchange languages with a native. Select a room in your right panel and start practicing your favourite language! Remember that you can check the meetup board to know when the chat room meetups take place..
        /// </summary>
        public static string ChatRoomsIntro {
            get {
                return ResourceManager.GetString("ChatRoomsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy provides videocalls between Langademy contacts specifying the conversation language. When you log in to Langademy you can use your state to let your contacts know in which languages you want to speak. If you don’t want to receive any calls, just set your state to busy. And remember that videocalls may have an impact on your Time Bank account. 
        ///.
        /// </summary>
        public static string DesktopState {
            get {
                return ResourceManager.GetString("DesktopState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy in 3 steps.
        /// </summary>
        public static string HelpAssistanceTitle {
            get {
                return ResourceManager.GetString("HelpAssistanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the chat room list, select a language room and start practicing it using video call technology..
        /// </summary>
        public static string HelpAssistanteStep1F1 {
            get {
                return ResourceManager.GetString("HelpAssistanteStep1F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can &lt;strong&gt;create meetups&lt;/strong&gt; to meet with more people at the Language Roulette.
        /// </summary>
        public static string HelpAssistanteStep1F2 {
            get {
                return ResourceManager.GetString("HelpAssistanteStep1F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Time banking:&lt;/strong&gt;.
        /// </summary>
        public static string HelpAssistanteStep2F1 {
            get {
                return ResourceManager.GetString("HelpAssistanteStep2F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you &lt;strong&gt;teach your native language&lt;/strong&gt; you will be rewarded with time in your account. If you &lt;strong&gt;practice other languages&lt;/strong&gt; you will be spending time from the time bank..
        /// </summary>
        public static string HelpAssistanteStep2F2 {
            get {
                return ResourceManager.GetString("HelpAssistanteStep2F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will &lt;strong&gt;start with 5 free hours&lt;/strong&gt; so you can practice the languages you want.
        /// </summary>
        public static string HelpAssistanteStep2F3 {
            get {
                return ResourceManager.GetString("HelpAssistanteStep2F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Langademy you can make videocalls with your contacts and decide which language you are going to practice. .
        /// </summary>
        public static string HelpAssistanteStep3F1 {
            get {
                return ResourceManager.GetString("HelpAssistanteStep3F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your state shows the languages you have defined in your profile. When these languages are enabled or disabled in your state, your contacts will know that you only want to receive calls in those languages that are enabled..
        /// </summary>
        public static string HelpAssistanteStep3F2 {
            get {
                return ResourceManager.GetString("HelpAssistanteStep3F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t want to receive calls, set your state to busy. Remember that these calls can affect your Time Bank account..
        /// </summary>
        public static string HelpAssistanteStep3F3 {
            get {
                return ResourceManager.GetString("HelpAssistanteStep3F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Rooms.
        /// </summary>
        public static string HelpChatRoom {
            get {
                return ResourceManager.GetString("HelpChatRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show again.
        /// </summary>
        public static string HelpDontShow {
            get {
                return ResourceManager.GetString("HelpDontShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can show this help at any time by clicking {0} at the foot of the page.
        /// </summary>
        public static string HelpShowhelpagain {
            get {
                return ResourceManager.GetString("HelpShowhelpagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpString {
            get {
                return ResourceManager.GetString("HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Langademy!.
        /// </summary>
        public static string HelpWelcome {
            get {
                return ResourceManager.GetString("HelpWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy state.
        /// </summary>
        public static string LangademyState {
            get {
                return ResourceManager.GetString("LangademyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Time Bank is a way to make language exchange fair for everyone at Langademy. This is how it works:.
        /// </summary>
        public static string TimeBankDescription {
            get {
                return ResourceManager.GetString("TimeBankDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will begin with 5 hours so you can practice the language you want..
        /// </summary>
        public static string TimeBankF1 {
            get {
                return ResourceManager.GetString("TimeBankF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, you will not be able to accumulate more than 10 hours in your Time Bank account..
        /// </summary>
        public static string TimeBankF2 {
            get {
                return ResourceManager.GetString("TimeBankF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your friends and you will get 30 extra minutes for each friend that is registered with your invitation. You can also earn hours for your Time Bank account  by following Langademy on Twitter and Facebook (+ 60 minutes)..
        /// </summary>
        public static string TimeBankF3 {
            get {
                return ResourceManager.GetString("TimeBankF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you practice a language that is not your native language, you spend time from your Time Bank account. If you speak to a non-native in your native language (minimum level: C2), you will be rewarded with time in your account..
        /// </summary>
        public static string TimeBankF4 {
            get {
                return ResourceManager.GetString("TimeBankF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls that are shorter than a minute have no cost.
        /// </summary>
        public static string TimeBankF5 {
            get {
                return ResourceManager.GetString("TimeBankF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Bank.
        /// </summary>
        public static string TimeBankTitle {
            get {
                return ResourceManager.GetString("TimeBankTitle", resourceCulture);
            }
        }
    }
}
