//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.ChatRooms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chatroom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chatroom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.ChatRooms.Chatroom", typeof(Chatroom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to meetup.
        /// </summary>
        public static string BackMeetup {
            get {
                return ResourceManager.GetString("BackMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string CRAdvanced {
            get {
                return ResourceManager.GetString("CRAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic partner finder.
        /// </summary>
        public static string CRAutomaticPartner {
            get {
                return ResourceManager.GetString("CRAutomaticPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credits.
        /// </summary>
        public static string CRBalance {
            get {
                return ResourceManager.GetString("CRBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginners.
        /// </summary>
        public static string CRBeginners {
            get {
                return ResourceManager.GetString("CRBeginners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy credits.
        /// </summary>
        public static string CRBuyCredits {
            get {
                return ResourceManager.GetString("CRBuyCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your calendar.
        /// </summary>
        public static string CRConditionCalendar {
            get {
                return ResourceManager.GetString("CRConditionCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create meetup.
        /// </summary>
        public static string CRCreateMeetup {
            get {
                return ResourceManager.GetString("CRCreateMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Wallet calls to start earning money.
        /// </summary>
        public static string CREnableWallet {
            get {
                return ResourceManager.GetString("CREnableWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide filtered.
        /// </summary>
        public static string CRHideFiltered {
            get {
                return ResourceManager.GetString("CRHideFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string CRIntermediate {
            get {
                return ResourceManager.GetString("CRIntermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a meetup.
        /// </summary>
        public static string CRMBCreateMeetup {
            get {
                return ResourceManager.GetString("CRMBCreateMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t chat with people right now? Is there little activity in the room? No problem! Go to the meetup board and create a meetup on the date an hour you want!.
        /// </summary>
        public static string CRMBSentence1 {
            get {
                return ResourceManager.GetString("CRMBSentence1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you create a meetup, other users will know when you will be available or joining this room again to chat or make videocalls..
        /// </summary>
        public static string CRMBSentence2 {
            get {
                return ResourceManager.GetString("CRMBSentence2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you looking for someone?.
        /// </summary>
        public static string CRMBTripBodyTitle {
            get {
                return ResourceManager.GetString("CRMBTripBodyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy Meetups.
        /// </summary>
        public static string CRMBTripTitle {
            get {
                return ResourceManager.GetString("CRMBTripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetups.
        /// </summary>
        public static string CRMeetupsTab {
            get {
                return ResourceManager.GetString("CRMeetupsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a meetup scheduled at {0}.
        /// </summary>
        public static string CRMeetupTime {
            get {
                return ResourceManager.GetString("CRMeetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetup topics.
        /// </summary>
        public static string CRMeetupTopics {
            get {
                return ResourceManager.GetString("CRMeetupTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natives.
        /// </summary>
        public static string CRNatives {
            get {
                return ResourceManager.GetString("CRNatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next meetups.
        /// </summary>
        public static string CRNextMeetups {
            get {
                return ResourceManager.GetString("CRNextMeetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no meetups scheduled for this room.
        /// </summary>
        public static string CRNoLanguageMeetups {
            get {
                return ResourceManager.GetString("CRNoLanguageMeetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meetups are scheduled at this time..
        /// </summary>
        public static string CRNoMeetup {
            get {
                return ResourceManager.GetString("CRNoMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody has proposed conversation topics for this meetup.
        /// </summary>
        public static string CRNoTopicsProposed {
            get {
                return ResourceManager.GetString("CRNoTopicsProposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natives.
        /// </summary>
        public static string CRNumNatives {
            get {
                return ResourceManager.GetString("CRNumNatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string CRNumParticipants {
            get {
                return ResourceManager.GetString("CRNumParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string CRParticipants {
            get {
                return ResourceManager.GetString("CRParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time bank calls.
        /// </summary>
        public static string CRTBAvailable {
            get {
                return ResourceManager.GetString("CRTBAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timebank call.
        /// </summary>
        public static string CRTBCall {
            get {
                return ResourceManager.GetString("CRTBCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string CRTopicsTab {
            get {
                return ResourceManager.GetString("CRTopicsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        public static string CRUsersCount {
            get {
                return ResourceManager.GetString("CRUsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string CRUsersTab {
            get {
                return ResourceManager.GetString("CRUsersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        public static string CRViewProfile {
            get {
                return ResourceManager.GetString("CRViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing in this chat room is free but you must have credits in your Wallet ({0}).
        /// </summary>
        public static string CRVisitorSentence {
            get {
                return ResourceManager.GetString("CRVisitorSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet calls.
        /// </summary>
        public static string CRWalletAvailable {
            get {
                return ResourceManager.GetString("CRWalletAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet call.
        /// </summary>
        public static string CRWalletCall {
            get {
                return ResourceManager.GetString("CRWalletCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to define your availability for Wallet Calls in your profile calendar. Go to {0} and fill your availability for this month..
        /// </summary>
        public static string CRWalletCondition1Content {
            get {
                return ResourceManager.GetString("CRWalletCondition1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill your availability:.
        /// </summary>
        public static string CRWalletCondition1Title {
            get {
                return ResourceManager.GetString("CRWalletCondition1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to your {0} and add your billing details.
        /// </summary>
        public static string CRWalletCondition2Content {
            get {
                return ResourceManager.GetString("CRWalletCondition2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your billing details:.
        /// </summary>
        public static string CRWalletCondition2Title {
            get {
                return ResourceManager.GetString("CRWalletCondition2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, update your rates for wallet calls now.
        /// </summary>
        public static string CRWalletConditionGrantedContent {
            get {
                return ResourceManager.GetString("CRWalletConditionGrantedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions for wallet calls updated.
        /// </summary>
        public static string CRWalletConditionGrantedTitle {
            get {
                return ResourceManager.GetString("CRWalletConditionGrantedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t update your rate in this language.
        /// </summary>
        public static string CRWalletConditionHeading {
            get {
                return ResourceManager.GetString("CRWalletConditionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to set the rate in this language you need to:.
        /// </summary>
        public static string CRWalletConditions {
            get {
                return ResourceManager.GetString("CRWalletConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string CRWalletConditionWallet {
            get {
                return ResourceManager.GetString("CRWalletConditionWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write here....
        /// </summary>
        public static string CRWriteTextbox {
            get {
                return ResourceManager.GetString("CRWriteTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meetup is over. You can join another or schedule a new one.
        /// </summary>
        public static string MeetupOverNotAccess {
            get {
                return ResourceManager.GetString("MeetupOverNotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must join the meetup before you can enter the room. Go back to the meetup page and click the &quot;{0}&quot; button.
        /// </summary>
        public static string NotParticipantNoAccess {
            get {
                return ResourceManager.GetString("NotParticipantNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This meetup is for speaking {0}. You must add this language to your profile if you want to attend the meetup.
        /// </summary>
        public static string NotSpeaksNoAccess {
            get {
                return ResourceManager.GetString("NotSpeaksNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all {0} meetups.
        /// </summary>
        public static string ViewAllLangMeetups {
            get {
                return ResourceManager.GetString("ViewAllLangMeetups", resourceCulture);
            }
        }
    }
}
