//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.BookLessons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.BookLessons.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book &lt;span class=&quot;text-bold&quot;&gt;{0}&lt;/span&gt; lessons.
        /// </summary>
        public static string BookLangTitle {
            get {
                return ResourceManager.GetString("BookLangTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and pay.
        /// </summary>
        public static string ConfirmAndPay {
            get {
                return ResourceManager.GetString("ConfirmAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dates are shown in your local time zone.
        /// </summary>
        public static string DatesLocal {
            get {
                return ResourceManager.GetString("DatesLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase a pack of 5 lessons (1 hour each).
        /// </summary>
        public static string FiveFeat1 {
            get {
                return ResourceManager.GetString("FiveFeat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher removed or updated the rates for this language. Please, refresh the page and book the lesson again.
        /// </summary>
        public static string NoLessonRates {
            get {
                return ResourceManager.GetString("NoLessonRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase 1 lesson (1 hour).
        /// </summary>
        public static string OneFeat1 {
            get {
                return ResourceManager.GetString("OneFeat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson purchase.
        /// </summary>
        public static string OpenLessonPurchase {
            get {
                return ResourceManager.GetString("OpenLessonPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your purchase is completed! Now you&apos;re being redirected to your Lesson Purchases app.
        /// </summary>
        public static string PurchaseProcessed {
            get {
                return ResourceManager.GetString("PurchaseProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your purchase is being processed. Please, wait....
        /// </summary>
        public static string PurchaseProcessing {
            get {
                return ResourceManager.GetString("PurchaseProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to reserve at least the date for one lesson.
        /// </summary>
        public static string ReserveOneLessonDate {
            get {
                return ResourceManager.GetString("ReserveOneLessonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rate.
        /// </summary>
        public static string SelectRate {
            get {
                return ResourceManager.GetString("SelectRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to sign in in order to continue with the purchase.
        /// </summary>
        public static string SignBefore {
            get {
                return ResourceManager.GetString("SignBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher has changed the availability calendar. Please, refresh the page and book the lesson again.
        /// </summary>
        public static string TeacherChangedAvailability {
            get {
                return ResourceManager.GetString("TeacherChangedAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase a pack of 10 lessons (1 hour each).
        /// </summary>
        public static string TenFeat1 {
            get {
                return ResourceManager.GetString("TenFeat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay per a 30 minutes lesson.
        /// </summary>
        public static string ThirtyFeat1 {
            get {
                return ResourceManager.GetString("ThirtyFeat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the best option for a first lesson.
        /// </summary>
        public static string ThirtyFeat2 {
            get {
                return ResourceManager.GetString("ThirtyFeat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Wallet balance has changed. Please, refresh the page and book again.
        /// </summary>
        public static string WalletBalanceChanged {
            get {
                return ResourceManager.GetString("WalletBalanceChanged", resourceCulture);
            }
        }
    }
}
