//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.TeacherProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.TeacherProfile.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce yourself, your teaching experience and your teaching methodology.
        /// </summary>
        public static string AboutMeEmpty {
            get {
                return ResourceManager.GetString("AboutMeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your description must be less than {1} characters long.
        /// </summary>
        public static string AboutMeMaxLength {
            get {
                return ResourceManager.GetString("AboutMeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add education.
        /// </summary>
        public static string AddEducation {
            get {
                return ResourceManager.GetString("AddEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add language.
        /// </summary>
        public static string AddLanguage {
            get {
                return ResourceManager.GetString("AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your teaching position at Langademy to your LinkedIn profile.
        /// </summary>
        public static string AddLinkedinTip {
            get {
                return ResourceManager.GetString("AddLinkedinTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Position.
        /// </summary>
        public static string AddPosition {
            get {
                return ResourceManager.GetString("AddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rates.
        /// </summary>
        public static string AddRates {
            get {
                return ResourceManager.GetString("AddRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your self introduction video.
        /// </summary>
        public static string AddVideo {
            get {
                return ResourceManager.GetString("AddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link to your introduction in Youtube or Vimeo.
        /// </summary>
        public static string AddVideoLabel {
            get {
                return ResourceManager.GetString("AddVideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at present.
        /// </summary>
        public static string AtPresent {
            get {
                return ResourceManager.GetString("AtPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book {0} lessons.
        /// </summary>
        public static string BookLessons {
            get {
                return ResourceManager.GetString("BookLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be less than {1} character long.
        /// </summary>
        public static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit position.
        /// </summary>
        public static string EditPosition {
            get {
                return ResourceManager.GetString("EditPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add details about your education that might be interesting for your potential students. Degrees, courses, certifications, etc..
        /// </summary>
        public static string EducationEmptyTextEdit {
            get {
                return ResourceManager.GetString("EducationEmptyTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string EducationTitle {
            get {
                return ResourceManager.GetString("EducationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing the education entry.
        /// </summary>
        public static string ErrorRemoveEducation {
            get {
                return ResourceManager.GetString("ErrorRemoveEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing the experience entry.
        /// </summary>
        public static string ErrorRemoveExperience {
            get {
                return ResourceManager.GetString("ErrorRemoveExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add details about your professional experience.
        /// </summary>
        public static string ExperienceEmptyTextEdit {
            get {
                return ResourceManager.GetString("ExperienceEmptyTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string ExperienceTitle {
            get {
                return ResourceManager.GetString("ExperienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five lessons.
        /// </summary>
        public static string FiveLessonsRate {
            get {
                return ResourceManager.GetString("FiveLessonsRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field From cannot be a future date.
        /// </summary>
        public static string FromGreaterThanNow {
            get {
                return ResourceManager.GetString("FromGreaterThanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field From cannot be grater than the field To.
        /// </summary>
        public static string FromGreaterThanTo {
            get {
                return ResourceManager.GetString("FromGreaterThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FromOrigin {
            get {
                return ResourceManager.GetString("FromOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I speak.
        /// </summary>
        public static string ISpeak {
            get {
                return ResourceManager.GetString("ISpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lessons.
        /// </summary>
        public static string LangLessons {
            get {
                return ResourceManager.GetString("LangLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of the lessons.
        /// </summary>
        public static string LanguageOfLessons {
            get {
                return ResourceManager.GetString("LanguageOfLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lessons.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New teacher.
        /// </summary>
        public static string NewTeacher {
            get {
                return ResourceManager.GetString("NewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t available ratings yet.
        /// </summary>
        public static string NoRatings {
            get {
                return ResourceManager.GetString("NoRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t received any ratings yet.
        /// </summary>
        public static string NoRatingsEditor {
            get {
                return ResourceManager.GetString("NoRatingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour lessons.
        /// </summary>
        public static string OneHourLessons {
            get {
                return ResourceManager.GetString("OneHourLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 lesson.
        /// </summary>
        public static string OneLesson {
            get {
                return ResourceManager.GetString("OneLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate per hour for purchasing 1 lesson.
        /// </summary>
        public static string OneLessonLong {
            get {
                return ResourceManager.GetString("OneLessonLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One lesson.
        /// </summary>
        public static string OneLessonRate {
            get {
                return ResourceManager.GetString("OneLessonRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay as you go.
        /// </summary>
        public static string PayAsYouGo {
            get {
                return ResourceManager.GetString("PayAsYouGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay as you go rate (Rate/hour).
        /// </summary>
        public static string PayAsYouGoLong {
            get {
                return ResourceManager.GetString("PayAsYouGoLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay as you go.
        /// </summary>
        public static string PayAsYouGoRate {
            get {
                return ResourceManager.GetString("PayAsYouGoRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private lessons.
        /// </summary>
        public static string PrivateLessons {
            get {
                return ResourceManager.GetString("PrivateLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check availability and book lessons.
        /// </summary>
        public static string PrLessonsBookTip {
            get {
                return ResourceManager.GetString("PrLessonsBookTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember! All rates are set in Langademy credits.
        /// </summary>
        public static string RatesCreditsRemember {
            get {
                return ResourceManager.GetString("RatesCreditsRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add rates for language lessons in your native languages.
        /// </summary>
        public static string RatesForNativeInfo {
            get {
                return ResourceManager.GetString("RatesForNativeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaks.
        /// </summary>
        public static string Speaks {
            get {
                return ResourceManager.GetString("Speaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teaches.
        /// </summary>
        public static string Teaches {
            get {
                return ResourceManager.GetString("Teaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten lessons.
        /// </summary>
        public static string TenLessonsRate {
            get {
                return ResourceManager.GetString("TenLessonsRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min lessons.
        /// </summary>
        public static string ThirtyMinLessons {
            get {
                return ResourceManager.GetString("ThirtyMinLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate per hour for purchasing 30 minutes lessons.
        /// </summary>
        public static string ThirtyMinLong {
            get {
                return ResourceManager.GetString("ThirtyMinLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes lesson.
        /// </summary>
        public static string ThirtyMinRate {
            get {
                return ResourceManager.GetString("ThirtyMinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string ThirtyMinutesRate {
            get {
                return ResourceManager.GetString("ThirtyMinutesRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To (or expected).
        /// </summary>
        public static string ToOrExpected {
            get {
                return ResourceManager.GetString("ToOrExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update video.
        /// </summary>
        public static string UpdateVideo {
            get {
                return ResourceManager.GetString("UpdateVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video introduction.
        /// </summary>
        public static string VideoIntroduction {
            get {
                return ResourceManager.GetString("VideoIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only embed Youtube or Vimeo videos (e.g. https://youtu.be/..., https://vimeo.com/0000000000).
        /// </summary>
        public static string VideoUrlMatchError {
            get {
                return ResourceManager.GetString("VideoUrlMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a valid Youtube or Vimeo url.
        /// </summary>
        public static string VideoUrlRequired {
            get {
                return ResourceManager.GetString("VideoUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you embed a video from Vimeo and you have defined &quot;domain-level privacy&quot; in your Vimeo account, make sure you add &quot;langademy.com&quot; to the list of authorized domains.
        /// </summary>
        public static string VimeoDomainTip {
            get {
                return ResourceManager.GetString("VimeoDomainTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid Vimeo url.
        /// </summary>
        public static string VimeoInvalidUrl {
            get {
                return ResourceManager.GetString("VimeoInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lessons.
        /// </summary>
        public static string XLessons {
            get {
                return ResourceManager.GetString("XLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate per hour for purchasing {0} lessons.
        /// </summary>
        public static string XLessonsLong {
            get {
                return ResourceManager.GetString("XLessonsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid Youtube url.
        /// </summary>
        public static string YoutubeInvalidUrl {
            get {
                return ResourceManager.GetString("YoutubeInvalidUrl", resourceCulture);
            }
        }
    }
}
