//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.DesktopSummary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Summary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.DesktopSummary.Summary", typeof(Summary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to add at least one language you are learning.
        /// </summary>
        public static string AddStudLangError {
            get {
                return ResourceManager.GetString("AddStudLangError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily suggestions.
        /// </summary>
        public static string DailySugs {
            get {
                return ResourceManager.GetString("DailySugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, this is your agenda for today.
        /// </summary>
        public static string HelloUser {
            get {
                return ResourceManager.GetString("HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meetups.
        /// </summary>
        public static string Meetups {
            get {
                return ResourceManager.GetString("Meetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private conversations.
        /// </summary>
        public static string PrConvs {
            get {
                return ResourceManager.GetString("PrConvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conversation requests unanswered.
        /// </summary>
        public static string ReqsRec {
            get {
                return ResourceManager.GetString("ReqsRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conversation requests answered.
        /// </summary>
        public static string ReqsSent {
            get {
                return ResourceManager.GetString("ReqsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search students.
        /// </summary>
        public static string SearchStudents {
            get {
                return ResourceManager.GetString("SearchStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search natives for timebanking conversations.
        /// </summary>
        public static string SearchTBNatives {
            get {
                return ResourceManager.GetString("SearchTBNatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search natives for paid conversations.
        /// </summary>
        public static string SearchWalletNatives {
            get {
                return ResourceManager.GetString("SearchWalletNatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should complete your profile.
        /// </summary>
        public static string TipCompleteProf {
            get {
                return ResourceManager.GetString("TipCompleteProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string TipCompleteProfAux {
            get {
                return ResourceManager.GetString("TipCompleteProfAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why?.
        /// </summary>
        public static string TipCompleteProfHelp {
            get {
                return ResourceManager.GetString("TipCompleteProfHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make yourself known and meet students scheduling a new meetup.
        /// </summary>
        public static string TipCreateMeetup {
            get {
                return ResourceManager.GetString("TipCreateMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule a meetup.
        /// </summary>
        public static string TipCreateMeetupAux {
            get {
                return ResourceManager.GetString("TipCreateMeetupAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I meet students?.
        /// </summary>
        public static string TipCreateMeetupHelp {
            get {
                return ResourceManager.GetString("TipCreateMeetupHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet conversation partners scheduling a new meetup.
        /// </summary>
        public static string TipCreateMeetupStud {
            get {
                return ResourceManager.GetString("TipCreateMeetupStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I meet new partners?.
        /// </summary>
        public static string TipCreateMeetupStudHelp {
            get {
                return ResourceManager.GetString("TipCreateMeetupStudHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set your availability for speaking in your native language. Otherwise students won&apos;t be able to request you private conversations.
        /// </summary>
        public static string TipEditAvailability {
            get {
                return ResourceManager.GetString("TipEditAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit my availability.
        /// </summary>
        public static string TipEditAvailabilityAux {
            get {
                return ResourceManager.GetString("TipEditAvailabilityAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to set availability.
        /// </summary>
        public static string TipEditAvailabilityHelp {
            get {
                return ResourceManager.GetString("TipEditAvailabilityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a native partner and request a private conversation.
        /// </summary>
        public static string TipSearchAndRequest {
            get {
                return ResourceManager.GetString("TipSearchAndRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search partners.
        /// </summary>
        public static string TipSearchAndRequestAux {
            get {
                return ResourceManager.GetString("TipSearchAndRequestAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I request a private conversation?.
        /// </summary>
        public static string TipSearchAndRequestHelp {
            get {
                return ResourceManager.GetString("TipSearchAndRequestHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have scheduled a paid conversation but you don&apos;t have enough credits in your wallet account. Please, purchase credits before the scheduled time or you won&apos;t be able to call.
        /// </summary>
        public static string TipWalletBalanceRunout {
            get {
                return ResourceManager.GetString("TipWalletBalanceRunout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy credits.
        /// </summary>
        public static string TipWalletBalanceRunoutAux {
            get {
                return ResourceManager.GetString("TipWalletBalanceRunoutAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before any student can pay you for private conversations you need to complete your billing address.
        /// </summary>
        public static string TipWalletNatBillingAddr {
            get {
                return ResourceManager.GetString("TipWalletNatBillingAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add billing address.
        /// </summary>
        public static string TipWalletNatBillingAddrAux {
            get {
                return ResourceManager.GetString("TipWalletNatBillingAddrAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Wallet conditions.
        /// </summary>
        public static string TipWalletNatBillingAddrHelp {
            get {
                return ResourceManager.GetString("TipWalletNatBillingAddrHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already meet the requirements to set your rate for paid conversations in {0}.
        /// </summary>
        public static string TipWalletNatSetRate {
            get {
                return ResourceManager.GetString("TipWalletNatSetRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to set my rate.
        /// </summary>
        public static string TipWalletNatSetRateHelp {
            get {
                return ResourceManager.GetString("TipWalletNatSetRateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need a minimum reputation for setting your rates as a native speaker. You can make timebanking video calls or wallet videocalls (for free) and ask students for their votes.
        /// </summary>
        public static string TipWalletNatZeroRepu {
            get {
                return ResourceManager.GetString("TipWalletNatZeroRepu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Langademy.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With native speakers.
        /// </summary>
        public static string WithNatives {
            get {
                return ResourceManager.GetString("WithNatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With students.
        /// </summary>
        public static string WithStudents {
            get {
                return ResourceManager.GetString("WithStudents", resourceCulture);
            }
        }
    }
}
