//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Blog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Blog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Blog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Blog.Blog", typeof(Blog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content is not available in {0}. This is the version in {1}.
        /// </summary>
        public static string AltLangInfo {
            get {
                return ResourceManager.GetString("AltLangInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string BlogBlog {
            get {
                return ResourceManager.GetString("BlogBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles about category &quot;{0}&quot;.
        /// </summary>
        public static string BlogCategoryTitle {
            get {
                return ResourceManager.GetString("BlogCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read articles about language learning and the world that surrounds us.
        /// </summary>
        public static string BlogSubtitle {
            get {
                return ResourceManager.GetString("BlogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles with the tag &quot;{0}&quot;.
        /// </summary>
        public static string BlogTagTitle {
            get {
                return ResourceManager.GetString("BlogTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Blog.
        /// </summary>
        public static string BlogTitle {
            get {
                return ResourceManager.GetString("BlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest posts.
        /// </summary>
        public static string GuestPosts {
            get {
                return ResourceManager.GetString("GuestPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write us to {0} and tell us something about you and about the post you want to write.
        /// </summary>
        public static string GuestText1 {
            get {
                return ResourceManager.GetString("GuestText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will give you a response as soon as possible!.
        /// </summary>
        public static string GuestText2 {
            get {
                return ResourceManager.GetString("GuestText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to write a post at Langademy?.
        /// </summary>
        public static string GuestTitle {
            get {
                return ResourceManager.GetString("GuestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find articles related to {0} at Langademy. Read our blog and learn about different languages..
        /// </summary>
        public static string RelatedPosts {
            get {
                return ResourceManager.GetString("RelatedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
    }
}
