//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.PrivateConversations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.PrivateConversations.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to speak with {0} click on Accept meetup to confirm.
        /// </summary>
        public static string AcceptToConfirm {
            get {
                return ResourceManager.GetString("AcceptToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooopss... it seems that {0} finally cancelled this conversation request.
        /// </summary>
        public static string ConversationFinallyCanceled {
            get {
                return ResourceManager.GetString("ConversationFinallyCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation not found.
        /// </summary>
        public static string ConversationNotFound {
            get {
                return ResourceManager.GetString("ConversationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooopss... it seems that {0} finally cancelled the conversation.
        /// </summary>
        public static string MeetupCancelledByNativeMessage {
            get {
                return ResourceManager.GetString("MeetupCancelledByNativeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooopss... it seems that you finally cancelled your conversation with {0}.
        /// </summary>
        public static string MeetupCancelledByStudentMessage {
            get {
                return ResourceManager.GetString("MeetupCancelledByStudentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooopss... it seems that {0} finally cancelled the conversation.
        /// </summary>
        public static string MeetupFinallyCanceled {
            get {
                return ResourceManager.GetString("MeetupFinallyCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My conversations.
        /// </summary>
        public static string MyConversations {
            get {
                return ResourceManager.GetString("MyConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} would like to practice {1} with you.
        /// </summary>
        public static string PracticeRequest {
            get {
                return ResourceManager.GetString("PracticeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wanted to practice {1} with you.
        /// </summary>
        public static string PracticeRequested {
            get {
                return ResourceManager.GetString("PracticeRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received requests.
        /// </summary>
        public static string ReceivedRequests {
            get {
                return ResourceManager.GetString("ReceivedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooopss... it seems that {0} cannot accept your conversation request.
        /// </summary>
        public static string RequestRejectedByNativeMessage {
            get {
                return ResourceManager.GetString("RequestRejectedByNativeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hasn&apos;t read your conversation request yet.
        /// </summary>
        public static string RequestStatusRequestedMessage {
            get {
                return ResourceManager.GetString("RequestStatusRequestedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received {0} more conversation requests for speaking at the same time. Check your conversation request inbox.
        /// </summary>
        public static string SameTimeRequests {
            get {
                return ResourceManager.GetString("SameTimeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent requests.
        /// </summary>
        public static string SentRequests {
            get {
                return ResourceManager.GetString("SentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string StudentReqAccepted {
            get {
                return ResourceManager.GetString("StudentReqAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept conversation.
        /// </summary>
        public static string StudentReqAcceptMeetup {
            get {
                return ResourceManager.GetString("StudentReqAcceptMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string StudentReqCancelled {
            get {
                return ResourceManager.GetString("StudentReqCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel conversation.
        /// </summary>
        public static string StudentReqCancelMeetup {
            get {
                return ResourceManager.GetString("StudentReqCancelMeetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel request.
        /// </summary>
        public static string StudentReqCancelRequest {
            get {
                return ResourceManager.GetString("StudentReqCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string StudentReqEnter {
            get {
                return ResourceManager.GetString("StudentReqEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooopss... it seems that you finally cancelled your conversation request.
        /// </summary>
        public static string StudentReqFinallyCancelled {
            get {
                return ResourceManager.GetString("StudentReqFinallyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow this link to enter the conversation room.
        /// </summary>
        public static string StudentReqFollowLink {
            get {
                return ResourceManager.GetString("StudentReqFollowLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation cancelled.
        /// </summary>
        public static string StudentReqMeetupCancelled {
            get {
                return ResourceManager.GetString("StudentReqMeetupCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string StudentReqMessages {
            get {
                return ResourceManager.GetString("StudentReqMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a pity that you didn&apos;t confirm the request earlier. Stay tuned to Langademy and do not miss more requests ;-).
        /// </summary>
        public static string StudentReqMissSentence {
            get {
                return ResourceManager.GetString("StudentReqMissSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You accepted another conversation request for the same time, so you cannot accept this one.
        /// </summary>
        public static string StudentReqOtherReq {
            get {
                return ResourceManager.GetString("StudentReqOtherReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string StudentReqPending {
            get {
                return ResourceManager.GetString("StudentReqPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal.
        /// </summary>
        public static string StudentReqProposal {
            get {
                return ResourceManager.GetString("StudentReqProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate on request date.
        /// </summary>
        public static string StudentReqRateOnRequest {
            get {
                return ResourceManager.GetString("StudentReqRateOnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string StudentReqReject {
            get {
                return ResourceManager.GetString("StudentReqReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string StudentReqRejected {
            get {
                return ResourceManager.GetString("StudentReqRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for.
        /// </summary>
        public static string StudentReqRequestFor {
            get {
                return ResourceManager.GetString("StudentReqRequestFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time banking conversation.
        /// </summary>
        public static string StudentReqTBConv {
            get {
                return ResourceManager.GetString("StudentReqTBConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet conversation.
        /// </summary>
        public static string StudentReqWalletConv {
            get {
                return ResourceManager.GetString("StudentReqWalletConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message.
        /// </summary>
        public static string StudentReqWriteMessage {
            get {
                return ResourceManager.GetString("StudentReqWriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timebanking conversation.
        /// </summary>
        public static string TBConversation {
            get {
                return ResourceManager.GetString("TBConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool! {0} and you are going to have a videocall. Stay tuned to Langademy and don&apos;t miss the conversation. Be on time!.
        /// </summary>
        public static string VideoCallMessage {
            get {
                return ResourceManager.GetString("VideoCallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet conversation.
        /// </summary>
        public static string WalletConversation {
            get {
                return ResourceManager.GetString("WalletConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You rejected this conversation with {0}.
        /// </summary>
        public static string YouConversationRejected {
            get {
                return ResourceManager.GetString("YouConversationRejected", resourceCulture);
            }
        }
    }
}
