//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Layout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Layout.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy is a social network to learn languages. It offers language exchange with natives all over the world so people can get fluent in a language. .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn languages, language exchange, get fluent, practice english, practice spanish, practice languages, native speakers, improve language level.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Langademy.
        /// </summary>
        public static string LAbout {
            get {
                return ResourceManager.GetString("LAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Langroulette you will meet new partners to practice the language you want to learn. Get fluent in a language while you meet new people!.
        /// </summary>
        public static string LRDescription {
            get {
                return ResourceManager.GetString("LRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to langroulette,language exchange,chat,tandem, fluency.
        /// </summary>
        public static string LRKeywords {
            get {
                return ResourceManager.GetString("LRKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langroulette-Tandem.
        /// </summary>
        public static string LRTitle {
            get {
                return ResourceManager.GetString("LRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy - Langademy.
        /// </summary>
        public static string MainPrivacy {
            get {
                return ResourceManager.GetString("MainPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions - Langademy.
        /// </summary>
        public static string MainTerms {
            get {
                return ResourceManager.GetString("MainTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Exchange.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Bank.
        /// </summary>
        public static string TBTitle {
            get {
                return ResourceManager.GetString("TBTitle", resourceCulture);
            }
        }
    }
}
