//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Layout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Layout.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy is an online language exchange community where you can practice foreign languages with natives all over the world..
        /// </summary>
        public static string DescAbout {
            get {
                return ResourceManager.GetString("DescAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the meetup board, you can create meetups to let the others know when you will be available to chat, or you can join the existing meetups .
        /// </summary>
        public static string DescMeetupBoard {
            get {
                return ResourceManager.GetString("DescMeetupBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.langademy.com is owned and operated by Eyelang S.L. We provide this Privacy Policy to better serve those who are concerned with how their personal information is being used online.
        /// </summary>
        public static string DescPrivacy {
            get {
                return ResourceManager.GetString("DescPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy is a social network to learn languages. It offers a language exchange space with natives all over the world for helping people to become fluent in foreign languages. .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy, learn languages, language exchange, become fluent, practice english, practice spanish, practice languages, native speakers, improve language level.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Langademy.
        /// </summary>
        public static string LAbout {
            get {
                return ResourceManager.GetString("LAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the Language Roulette you will meet new partners to practice the language you want to learn. Become fluent in a language while you meet new people!.
        /// </summary>
        public static string LRDescription {
            get {
                return ResourceManager.GetString("LRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language roulette,language exchange,chat,tandem, fluency.
        /// </summary>
        public static string LRKeywords {
            get {
                return ResourceManager.GetString("LRKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Roulette-Tandem.
        /// </summary>
        public static string LRTitle {
            get {
                return ResourceManager.GetString("LRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy - Langademy.
        /// </summary>
        public static string MainPrivacy {
            get {
                return ResourceManager.GetString("MainPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions - Langademy.
        /// </summary>
        public static string MainTerms {
            get {
                return ResourceManager.GetString("MainTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Exchange.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Bank.
        /// </summary>
        public static string TBTitle {
            get {
                return ResourceManager.GetString("TBTitle", resourceCulture);
            }
        }
    }
}
