//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.LessonPurchases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.LessonPurchases.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All purchases.
        /// </summary>
        public static string AllPurchases {
            get {
                return ResourceManager.GetString("AllPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel purchase.
        /// </summary>
        public static string CancelPurchase {
            get {
                return ResourceManager.GetString("CancelPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been succesfully processed.
        /// </summary>
        public static string LessonPurchaseActionProcessed {
            get {
                return ResourceManager.GetString("LessonPurchaseActionProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is being processed. Please, wait....
        /// </summary>
        public static string LessonPurchaseActionProcessing {
            get {
                return ResourceManager.GetString("LessonPurchaseActionProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson purchases.
        /// </summary>
        public static string LessonPurchasesTitle {
            get {
                return ResourceManager.GetString("LessonPurchasesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t purchased any lessons.
        /// </summary>
        public static string NoPurchases {
            get {
                return ResourceManager.GetString("NoPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot cancel your purchase while lesson scheduling operations are in progress.
        /// </summary>
        public static string PendingSchOpsCancelPError {
            get {
                return ResourceManager.GetString("PendingSchOpsCancelPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cancelled the purchase.
        /// </summary>
        public static string PurchaseCancelledByYou {
            get {
                return ResourceManager.GetString("PurchaseCancelledByYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher confirmed your purchase.
        /// </summary>
        public static string PurchaseConfirmedByTeacher {
            get {
                return ResourceManager.GetString("PurchaseConfirmedByTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher rejected your purchase.
        /// </summary>
        public static string PurchaseRejectedByTeacher {
            get {
                return ResourceManager.GetString("PurchaseRejectedByTeacher", resourceCulture);
            }
        }
    }
}
