//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.LessonSalesCommon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SalesCommons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SalesCommons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.LessonSalesCommon.SalesCommons", typeof(SalesCommons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept reschedule.
        /// </summary>
        public static string AcceptReschedule {
            get {
                return ResourceManager.GetString("AcceptReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept solution.
        /// </summary>
        public static string AcceptSolution {
            get {
                return ResourceManager.GetString("AcceptSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept unschedule.
        /// </summary>
        public static string AcceptUnschedule {
            get {
                return ResourceManager.GetString("AcceptUnschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string AllCancelled {
            get {
                return ResourceManager.GetString("AllCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string AllCompleted {
            get {
                return ResourceManager.GetString("AllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string AllConfirmed {
            get {
                return ResourceManager.GetString("AllConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string AllRejected {
            get {
                return ResourceManager.GetString("AllRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string CancelledPlural {
            get {
                return ResourceManager.GetString("CancelledPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel mediation.
        /// </summary>
        public static string CancelMediation {
            get {
                return ResourceManager.GetString("CancelMediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel report.
        /// </summary>
        public static string CancelReport {
            get {
                return ResourceManager.GetString("CancelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reschedule.
        /// </summary>
        public static string CancelReschedule {
            get {
                return ResourceManager.GetString("CancelReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel unschedule.
        /// </summary>
        public static string CancelUnschedule {
            get {
                return ResourceManager.GetString("CancelUnschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain additional details about the issue (Your comments will be submitted to your teacher).
        /// </summary>
        public static string CommentIssueStudent {
            get {
                return ResourceManager.GetString("CommentIssueStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain additional details about the issue (Your comments will be submitted to your student).
        /// </summary>
        public static string CommentIssueTeacher {
            get {
                return ResourceManager.GetString("CommentIssueTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete lesson.
        /// </summary>
        public static string CompleteLesson {
            get {
                return ResourceManager.GetString("CompleteLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the new date.
        /// </summary>
        public static string ConfirmNewDate {
            get {
                return ResourceManager.GetString("ConfirmNewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date.
        /// </summary>
        public static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to solve this issue?.
        /// </summary>
        public static string HowSolveIssue {
            get {
                return ResourceManager.GetString("HowSolveIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lesson pack is completed.
        /// </summary>
        public static string LessonPackCompleted {
            get {
                return ResourceManager.GetString("LessonPackCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lessons.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lessons.
        /// </summary>
        public static string LessonsLang {
            get {
                return ResourceManager.GetString("LessonsLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why does your teacher disagree with your solution?.
        /// </summary>
        public static string MedDisagreementStudent {
            get {
                return ResourceManager.GetString("MedDisagreementStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why does your student disagree with your solution?.
        /// </summary>
        public static string MedDisagreementTeacher {
            get {
                return ResourceManager.GetString("MedDisagreementTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you had issues with this lesson and you didn&apos;t agree on a solution with your teacher using the Report Issue feature, you can request Langademy&apos;s mediation. Our team decision will be final. Please, complete the form below and we will contact you (take into account that your teacher will also see what you write).
        /// </summary>
        public static string MedIntroStudent {
            get {
                return ResourceManager.GetString("MedIntroStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you had issues with this lesson and you didn&apos;t agree on a solution with your student using the Report Issue feature, you can request Langademy&apos;s mediation. Our team decision will be final. Please, complete the form below and we will contact you (take into account that your student will also see what you write).
        /// </summary>
        public static string MedIntroTeacher {
            get {
                return ResourceManager.GetString("MedIntroTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, describe the problem you need mediation for as accurately as posible.
        /// </summary>
        public static string MedIssueDescr {
            get {
                return ResourceManager.GetString("MedIssueDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which solution do you propose?.
        /// </summary>
        public static string MedProposedSol {
            get {
                return ResourceManager.GetString("MedProposedSol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherIssue {
            get {
                return ResourceManager.GetString("OtherIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunds.
        /// </summary>
        public static string Refunds {
            get {
                return ResourceManager.GetString("Refunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject reschedule.
        /// </summary>
        public static string RejectReschedule {
            get {
                return ResourceManager.GetString("RejectReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RejectSolution.
        /// </summary>
        public static string RejectSolution {
            get {
                return ResourceManager.GetString("RejectSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject unschedule.
        /// </summary>
        public static string RejectUnschedule {
            get {
                return ResourceManager.GetString("RejectUnschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length: {0} characters.
        /// </summary>
        public static string RepIssueMaxLength {
            get {
                return ResourceManager.GetString("RepIssueMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report issue.
        /// </summary>
        public static string ReportIssue {
            get {
                return ResourceManager.GetString("ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request mediation.
        /// </summary>
        public static string RequestMediation {
            get {
                return ResourceManager.GetString("RequestMediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        public static string Reschedule {
            get {
                return ResourceManager.GetString("Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule the lesson.
        /// </summary>
        public static string RescheduleSolution {
            get {
                return ResourceManager.GetString("RescheduleSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled lessons.
        /// </summary>
        public static string ScheduledLessons {
            get {
                return ResourceManager.GetString("ScheduledLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the new date.
        /// </summary>
        public static string SelectNewDate {
            get {
                return ResourceManager.GetString("SelectNewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one issue to report.
        /// </summary>
        public static string SelectReportIssues {
            get {
                return ResourceManager.GetString("SelectReportIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the lesson (50% will be refunded).
        /// </summary>
        public static string StuCancelAndRefundHalfSolution {
            get {
                return ResourceManager.GetString("StuCancelAndRefundHalfSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the lesson (100% will be refunded).
        /// </summary>
        public static string StuCancelAndRefundSolution {
            get {
                return ResourceManager.GetString("StuCancelAndRefundSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark lesson as Completed (50% will be paid).
        /// </summary>
        public static string StuCollectHalfSolution {
            get {
                return ResourceManager.GetString("StuCollectHalfSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark lesson as Completed (100% will be paid).
        /// </summary>
        public static string StuCollectSolution {
            get {
                return ResourceManager.GetString("StuCollectSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student left early.
        /// </summary>
        public static string StudentEarlyIssue {
            get {
                return ResourceManager.GetString("StudentEarlyIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student arrived late.
        /// </summary>
        public static string StudentLateIssue {
            get {
                return ResourceManager.GetString("StudentLateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student missed the lesson.
        /// </summary>
        public static string StudentMissedIssue {
            get {
                return ResourceManager.GetString("StudentMissedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The studentrequested mediation to solve an issue. Langademy team will contact you.
        /// </summary>
        public static string StudentRequestedMediation {
            get {
                return ResourceManager.GetString("StudentRequestedMediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student experienced technical problems.
        /// </summary>
        public static string StudentTechnicalIssue {
            get {
                return ResourceManager.GetString("StudentTechnicalIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher left early.
        /// </summary>
        public static string TeacherEarlyIssue {
            get {
                return ResourceManager.GetString("TeacherEarlyIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher arrived late.
        /// </summary>
        public static string TeacherLateIssue {
            get {
                return ResourceManager.GetString("TeacherLateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher missed the lesson.
        /// </summary>
        public static string TeacherMissedIssue {
            get {
                return ResourceManager.GetString("TeacherMissedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher requested mediation to solve an issue. Langademy team will contact you.
        /// </summary>
        public static string TeacherRequestedMediation {
            get {
                return ResourceManager.GetString("TeacherRequestedMediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teacher experienced technical problems.
        /// </summary>
        public static string TeacherTechnicalIssue {
            get {
                return ResourceManager.GetString("TeacherTechnicalIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the lesson (50% will be refunded).
        /// </summary>
        public static string TeCancelAndRefundHalfSolution {
            get {
                return ResourceManager.GetString("TeCancelAndRefundHalfSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the lesson (100% will be refunded).
        /// </summary>
        public static string TeCancelAndRefundSolution {
            get {
                return ResourceManager.GetString("TeCancelAndRefundSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark lesson as Completed (50% will be collected).
        /// </summary>
        public static string TeCollectHalfSolution {
            get {
                return ResourceManager.GetString("TeCollectHalfSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark lesson as Completed (100% will be collected).
        /// </summary>
        public static string TeCollectSolution {
            get {
                return ResourceManager.GetString("TeCollectSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed.
        /// </summary>
        public static string Unconfirmed {
            get {
                return ResourceManager.GetString("Unconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unschedule.
        /// </summary>
        public static string Unschedule {
            get {
                return ResourceManager.GetString("Unschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View by.
        /// </summary>
        public static string ViewBy {
            get {
                return ResourceManager.GetString("ViewBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You requested mediation to solve an issue. Langademy team will contact you.
        /// </summary>
        public static string YouRequestedMediation {
            get {
                return ResourceManager.GetString("YouRequestedMediation", resourceCulture);
            }
        }
    }
}
