//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Mails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Mails.Mail", typeof(Mail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s calendar is updated.
        /// </summary>
        public static string AvailableRequest {
            get {
                return ResourceManager.GetString("AvailableRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} people have updated their calendars.
        /// </summary>
        public static string AvailableRequests {
            get {
                return ResourceManager.GetString("AvailableRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has accepted your conversation request.
        /// </summary>
        public static string ConversationAccepted {
            get {
                return ResourceManager.GetString("ConversationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a converstaion scheduled for today.
        /// </summary>
        public static string ConversationAlert {
            get {
                return ResourceManager.GetString("ConversationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have some conversations scheduled for today.
        /// </summary>
        public static string ConversationAlerts {
            get {
                return ResourceManager.GetString("ConversationAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langademy Invitation.
        /// </summary>
        public static string InvitationSubject {
            get {
                return ResourceManager.GetString("InvitationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email.
        /// </summary>
        public static string MailConfirmEmail {
            get {
                return ResourceManager.GetString("MailConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection request.
        /// </summary>
        public static string MailFriendRequest {
            get {
                return ResourceManager.GetString("MailFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New meetup participants.
        /// </summary>
        public static string MailNewMeetupParticipants {
            get {
                return ResourceManager.GetString("MailNewMeetupParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone wants to have a conversation with you.
        /// </summary>
        public static string NewConversationRequests {
            get {
                return ResourceManager.GetString("NewConversationRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} meetup.
        /// </summary>
        public static string NewMeetupMail {
            get {
                return ResourceManager.GetString("NewMeetupMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New meetups for you!.
        /// </summary>
        public static string NewMeetupMails {
            get {
                return ResourceManager.GetString("NewMeetupMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover your password.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a meetup scheduled for today.
        /// </summary>
        public static string PublicMeetupAlert {
            get {
                return ResourceManager.GetString("PublicMeetupAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We miss you!.
        /// </summary>
        public static string VisitReminder {
            get {
                return ResourceManager.GetString("VisitReminder", resourceCulture);
            }
        }
    }
}
